trigger:
  tags:
    include:
      - "*"

stages:
  - stage: Build
    jobs:
      - job: Build_Solution
        pool: Default
        steps:
        - task: CopyFiles@2
          displayName: 'Copy Artifact to Artifact Staging Directory'
          inputs:
            Contents: artifact.txt
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        
        - task: PublishBuildArtifacts@1
          displayName: 'Publish Artifacts'

        - task: GitHubRelease@1
          displayName: 'Create GitHub Release'
          condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
          inputs:
            gitHubConnection: 'ShaylenReddy42_OAuth'
            repositoryName: '$(Build.Repository.Name)'
            action: create
            tagSource: userSpecifiedTag
            tag: $(Build.SourceBranchName)
            title: 'Release v$(Build.SourceBranchName)'
            releaseNotesSource: filePath
            releaseNotesFilePath: '$(Build.SourcesDirectory)/docs/releases/v$(Build.SourceBranchName).md'
            assets: '$(Build.ArtifactStagingDirectory)/*'
            addChangeLog: true
            changeLogCompareToRelease: lastFullRelease
            changeLogType: commitBased
